Update cfarm to support projects that have git submodules.

diff --git a/templates/post-receive b/templates/post-receive
--- a/templates/post-receive
+++ b/templates/post-receive
@@ -1,2 +1,26 @@
 #!/bin/sh
-GIT_WORK_TREE=%(src_location)s git checkout -f
+#
+# An example hook script to update the working tree, including its
+# submodules, after receiving a push.
+#
+# This hook requires  receive.denyCurrentBranch to be explicitly set to false.
+#
+# Read standard input or hook will fail
+while read oldrev newrev refname
+do
+:
+done
+
+export GIT_WORK_TREE=%(src_location)s
+
+# Unset GIT_DIR or the universe will implode
+unset GIT_DIR
+
+# Change directory to the working tree; exit on failure
+cd `git config --get core.worktree` || exit
+
+# Force checkout
+git checkout --force
+
+# Force update submodules
+git submodule update --init --recursive --force
